[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
src_dir = firmware/src
lib_dir = firmware/lib

lib_deps =
    fastled/FastLED@^3.6.0

build_flags =
    -Wall -Wextra
    -DNUM_LEDS=30
    -DMAX_NODES=15
    -Ifirmware/include

[env:test]
platform = espressif32
board = esp32dev
framework = arduino
build_type = debug
src_dir = firmware/src
lib_dir = firmware/lib
lib_deps =
    fastled/FastLED@^3.6.0
build_flags =
    -Wall -Wextra -DTEST_BUILD
    -Ifirmware/include
